### ISSUE TITLE
Badmatch error when attempting to authenticate using a correct username and password

### ISSUE THREAD

**Issue by Stratus3D** [inaka/hexer#28]
I am using hexer with hexer.mk. I installed hexer.mk and I attempted to authenticate with my hex user account but I kept getting an error:

```
Username: Stratus3D
Password: -
Generating API key...
Error: Generation of API key failed ({badmatch,
                                  #{timeout => 5000,
                                    handle_event => undefined,
                                    headers => [{<<"Authorization">>,
                                      <<"Basic ....">>},
                                     {<<"Accept">>,
                                      <<"application/vnd.hex+erlang">>},
                                     {<<"Content-Type">>,
                                      <<"application/vnd.hex+erlang">>}],
                                    async => false,
                                    async_mode => binary}})
```

I assumed this was due to an incorrect password, so I logged out and then logged in again with the same account on an Elixir project. I was able to authenticate using mix with the username and password I had been using. The error that was printed to STDOUT was the same regardless of whether the username/password combination was correct or not.

**Comment by Stratus3D** [comment]
I cloned down hexer and I tried authenticating. At first I got the same error. After making a few changes, compiling them, then reverting them, and then recompiling them, authentication started working. I am not sure what changed, since I reverted all my changes to the Erlang source code. 

This was what I used to rebuild the hexer escript after changes to the Erlang code:

```
rm hexer.config && rm -r bin/ && make clean && make && make escript
```

I think this would remove everything from prior builds and user.auth calls.

**Comment by elbrujohalcon** [comment]
@Stratus3D You should probably change your password on hex, since it's kinda visible now in the description of this issue. In any case, you can check the password that's sent as part of the authentication (`U3RyYXR1czNEOmdtYWtlcl43` is in base64) to see if hexer is sending the proper characters to hex.pm
And I repeat: you should change your password now.

Please let us know what you find, we'll be investigating ourselves as well, but it works with our user. My feeling is that special characters are not correctly managed by either the shell, hexer, base64 or shotgun

**Comment by Stratus3D** [comment]
Password changed and comment updated. 

I think it's safe to rule out the shell as hex was working with my old password (and hexer worked once with it).  I'll keep digging and see if I can figure out where the issue is.

**Comment by elbrujohalcon** [comment]
@Stratus3D: any news? @davecaos run a couple of tests with different users and passwords and it worked all the time.
Maybe it was a glitch in hex.pm services?

**Comment by Stratus3D** [comment]
It may be a hex.pm glitch, but it isn't a transient glitch as the same error was printed when I tried to authenticating with hexer.mk today. 

Is the hexer escript rebuild command I am using correct (in the comment above)? A badmatch error should be pretty easy for me to track down, but I want to make sure I am building the hexer escript correctly. Thanks!

**Comment by elbrujohalcon** [comment]
@Stratus3D your command should indeed remove everything from previous builds. This one should do the same:

``` bash
rm -rf bin/ hexer.config && make distclean && make escript
```
