### ISSUE TITLE
Bad formatting for requirements

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/hexer#38]
As described in inaka/hexer.mk#15:

The requirements in the package metadata is being published in the wrong format. If the take katana v0.2.20 as example the requirements are listed as `[{<<"xref_runner">>, <<"0.2.4">>}, {<<"inaka_aleppo">>, <<"0.9.5">>}]` but the should be in this format:

``` erlang
[{<<"xref_runner">>, [
  {<<"app">>, <<"xref_runner">>},
  {<<"requirement">>, <<"0.2.4">>},
  {<<"optional">>, false}]},
 {<<"inaka_aleppo">>, [
  {<<"app">>, <<"inaka_aleppo">>},
  {<<"requirement">>, <<"0.9.5">>},
  {<<"optional">>, false}]}
]
```

Specification: https://github.com/hexpm/specifications/blob/master/package_metadata.md

**Comment by elbrujohalcon** [comment]
@ericmj: Just to confirm, the actual value in the example should be…

``` erlang
[{<<"xref_runner">>, [
  {<<"app">>, <<"xref_runner">>},
  {<<"requirement">>, <<"0.2.4">>},
  {<<"optional">>, false}]},
 {<<"inaka_aleppo">>, [
  {<<"app">>, <<"aleppo">>},
  {<<"requirement">>, <<"0.9.5">>},
  {<<"optional">>, false}]}
]
```

In other words, the app name in the second package should be `aleppo`, which is the actual app name, although the package is called `inaka_aleppo`. Is that correct?

**Comment by ericmj** [comment]
That is exactly correct.
