### ISSUE TITLE
Erlang.mk 3rd-party plug-in

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/hexer#4]
Recently-ish @essen added support for external plugins in [erlang.mk](http://github.com/ninenines/erlang.mk), which can be loaded by using `PLUGIN_DEP = hexer`, for example. More info [here](https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/external_plugins.asciidoc)

**Comment by jfacorro** [comment]
Implemented a separate plugin in inaka/hexer.mk
